[phases.setup]
aptPkgs = ["ffmpeg", "libsodium-dev"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -U yt-dlp",
  "pip install -r requirements.txt"
]

[start]
cmd = "python3 bot.py"